### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by yaasin12** [Kaweees/Discord-Chess-Bot#2]
C:\Users\Yass\Desktop\Discord-Chess-Bot>py bot.py
Traceback (most recent call last):
  File "C:\Users\Yass\Desktop\Discord-Chess-Bot\bot.py", line 179, in <module>
    client.run(getToken())
  File "C:\Users\Yass\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 718, in run
    return future.result()
  File "C:\Users\Yass\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 697, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Yass\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 660, in start
    await self.login(*args, bot=bot)
  File "C:\Users\Yass\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 509, in login
    await self.http.static_login(token.strip(), bot=bot)
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by Kaweees** [comment]
I think I fixed your issue through #3. Can you try following the instructions detailed on the pull request and try again? Are you running locally or through Heroku?
